export const skills = [
  { skill: "HTML" },
  { skill: "CSS" },
  { skill: "JavaScript" },
  { skill: "TypeScript" },
  { skill: "React" },
  { skill: "Node.js" },
  { skill: "jQuery" },
  { skill: "Next.js" },
  { skill: "Tailwind CSS" },
  { skill: "Material UI" },
  { skill: "Styled Components" },
  { skill: "REST API" },
  { skill: "GraphQL" },
  { skill: "Apollo Client" },
  { skill: "Git" },
  { skill: "GitLab" },
  { skill: "GitHub" },
  { skill: "GitHub Actions" },
  { skill: "Terraform" },
  { skill: "Jest" },
  { skill: "Cypress" },
  { skill: "AWS" },
  { skill: "Google OAuth" },
  { skill: "Wordpress" },
  { skill: "Elementor" },
];

export const projects = [
  {
    name: "Lunch App",
    description: "Lunch App is a portal for vendors to request instant payments.",
    techStack: [
      "React",
      "Typescript",
      "jQuery",
      "Tailwind CSS",
      "Vite",
      "pnpm",
      "REST API",
      "GraphQL",
      "Pothos",
      "Prisma",
      "Apollo Client",
      "AWS API Gateway",
      "AWS Lambda",
      "AWS DynamoDB",
      "AWS CloudSearch",
      "AWS Secrets Manager",
      "AWS Cognito",
      "AWS S3",
      "AWS CloudFront",
      "AWS CloudWatch",
      "Terraform",
      "Github Actions",
      "Third Party API - Modern Treasury, Plaid, ESIG",
    ],
    images: ["/lunch-app-0.png", "/lunch-app-1.png", "/lunch-app-2.png"],
    link: "https://app.lunchpayments.com/",
  },
  {
    name: "Lunch Ops",
    description:
      "Lunch Ops is an internal tool created a single source of truth for orders, payments, and collections.",
    techStack: [
      "React",
      "Typescript",
      "Styled Components",
      "REST API",
      "AWS API Gateway",
      "AWS Lambda",
      "AWS DynamoDB",
      "AWS Secrets Manager",
      "AWS Cognito",
      "Google Cloud OAuth",
      "AWS S3",
      "AWS CloudFront",
      "AWS CloudWatch",
      "Third Party API - Modern Treasury, Plaid",
    ],
    images: ["/lunch-ops-0.png", "/lunch-ops-1.png", "/lunch-ops-2.png"],
    link: "https://ops.lunchpayments.com/",
  },
  {
    name: "Lunch Marketing",
    description: "Lunch Marketing is a marketing site for Lunch Payments and new customers.",
    images: ["/lunch-marketing-0.png", "/lunch-marketing-1.png"],
    link: "https://lunchpayments.com/",
  },
  {
    name: "ALLO Customer Portal",
    description:
      "Customer Portal is a customer facing site for Allo Fiber where customers can sign up for services.",
    techStack: [
      "React",
      "Typescript",
      "Material UI",
      "Styled Components",
      "GraphQL",
      "AWS Amplify",
      "Python",
      "yarn",
      "nx monorepo",
      "Figma",
      "Third Party API - LaunchDarkly",
    ],
    images: ["/allo-cp-0.png", "/allo-cp-1.png", "/allo-cp-2.png", "/allo-cp-3.png"],
    link: "https://customer.allofiber.com/",
  },
  {
    name: "ALLO Agent Portal",
    description:
      "Agent Portal is an internal tool where ALLO employees can perform numerous tasks.",
    techStack: [
      "React",
      "Typescript",
      "Material UI",
      "Styled Components",
      "GraphQL",
      "AWS Amplify",
      "Python",
      "yarn",
      "nx monorepo",
      "Figma",
      "Third Party API - LaunchDarkly",
    ],
    images: ["/allo-ap-0.png", "/allo-ap-1.png", "/allo-ap-2.png"],
    link: "https://agent.allofiber.org/home",
  },
  {
    name: "The Pony Express",
    description: "The Pony Express is a website for the Pony Express Company.",
    techStack: ["WordPress", "Elementor", "HTML", "CSS", "JavaScript", "PHP"],
    images: ["/pony-0.png", "/pony-1.png", "/pony-2.png"],
    link: "https://theponyexpressrocks.org/rebuilding-the-pony-express/",
  },
];
